### ISSUE TITLE
For downstream tasks, to extract the 12layer output feature, should I use the linear project (pred_head) layer？

### ISSUE THREAD

**Issue by splinter21** [vectominist/spin#1]
Good job! Congratulations!
If I want to use it to extract the ssl feature for downstream tasks, should I use the layer12 output (768dim), or the layer12 output after pred_head (256dim)?

**Comment by vectominist** [comment]
Thanks for your interest!
For [SUPERB](https://arxiv.org/abs/2105.01051) experiments, we use all 12 encoder layers + CNN features (all 768 dimensions) with a weighted-sum mechanism.
Although not mentioned in the paper, we found that the encoder's features generally offer better performance than the predicted 256-dimensional features.

**Comment by splinter21** [comment]
Thank you, this has solved my issue！
